# Numpy, Astropy, and SciPy exercises

## Numpy

### 1) For-loop, list comprehension, or NumPy?

Use the following code to generate an array of 10 floats randomly between 0-100 as `ls_numpy` and store the same numbers as a Python list as `ls_list`

In [ ]:
import numpy as np

ls_numpy = np.random.uniform(low=0, high=100, size=10)
ls_list = list(ls_numpy)

Now, modify the list/array by dividing each item/element by the mean of the entire set. Do this with:

1. For-loop
2. List comprehension
3. NumPy

Make sure each method outputs the same numbers

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

### 2) Manipulating arrays

Using NumPy, create the following arrays:
1. **a)** Three 1x3 arrays with values that range from 0-2, 3-5, and 6-8 respectively
```python
array([0, 1, 2])
array([3, 4, 5])
array([6, 7, 8])
```
   **b)** A 5x5 matrix/2darray with 1 on the borders and 0 inside
```python
array([[1 1 1 1 1],
          [1 0 0 0 1],
          [1 0 0 0 1],
          [1 0 0 0 1],
          [1 1 1 1 1]])
```

Now that you have done this, do the following:

2. **a)** Stack your three 1x3 arrays into a single 3x3 matrix
```python
array([[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]])
```

   **b)** Add a new border of zeros to the 5x5 matrix, making it a 7x7 matrix
```python
array([[0 0 0 0 0 0 0]  
          [0 1 1 1 1 1 0],
          [0 1 0 0 0 1 0],
          [0 1 0 0 0 1 0],
          [0 1 0 0 0 1 0],
          [0 1 1 1 1 1 0],
          [0 0 0 0 0 0 0]])
```

<details>
  <summary>Click here when you are done!</summary>

- For 2. **a)** [**`np.vstack()`**](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) lets you stack arrays vertically into a new array.
    
- For 2. **b)** We can add zeros to the edge of our arrays with [**`np.pad()`**](https://numpy.org/doc/stable/reference/generated/numpy.pad.html?highlight=pad#numpy.pad)
    
Redo 2. **a)** and **b)** with these functions.
</details>

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

### 3) Reshaping arrays

Create an array of size 12 and then

1. Reshape the array to be 3x4 and 4x3 with [**`np.reshape()`**](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html?highlight=reshape#numpy.reshape)
2. Reshape it back down again using both **`np.reshape()`**, **`np.flat()`**, and **`np.ravel()`**
3. Create an 18x3 array skipping the first and last rows of the original
4. Take the 12 array and expand its dimension once with [**`np.expand_dims()`**](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html#numpy.expand_dims) and then expand another dimension with [**`np.newaxis`**](https://numpy.org/doc/stable/reference/constants.html?highlight=newaxis#numpy.newaxis)

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

### 4) Masking, slicing, indexing

Create an array of shape 20x3 with `np.random.randint()`. Now extract the following into new variables:
1. The three separate columns
2. Four different 2x2 arrays that corresponds to the corners of the 20x3 array
3. Only the even rows, which creates a 10x3 array

Once this is done do the following:
1. Create a new 1x8 array containing the mean of each of the above new arrays
2. Replace the largest value in the original 20x3 array with the sum of its row number and column number
3. Create an 18x3 array skipping the first and last rows of the original

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

### 5)  Matrix product

Create a 3x2 matrix and a 2x4 matrix using the following:

In [ ]:
A = np.array([[8, 9], [10, 2], [5, 4]])
B = np.array([[6, 6, 2, 1], [1, 1, 0, 4]])

print(f'A: \n{A}\n')
print(f'B: \n{B}\n')

Now perform the matrix multiplication $C = \pmb{AB}$ which should result in the following 3x4 matrix:

```python 
C:  [[57, 57, 16, 44],
     [62, 62, 20, 18],
     [34, 34, 10, 21]]
```

<details>
  <summary>Click here for an explanation.</summary>

Matrix multiplication between a 4x2 matrix **A** and a 2x3 matrix **B** is done with their respective elements in the way shown in the figure
![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)
    
If the matrices have the elements 
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/9196c0c24ad20c3b18582bc78785fa405d91c7c3)
Then the elements of **C** are:
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/ee372c649dea0a05bf1ace77c9d6faf051d9cc8d) 
  
</details>
<br>
<details>
  <summary>Click here for a hint.</summary>

There are three different tools (two NumPy and one Python) that can help you perform this exercises. Matrix multiplication can be done using either
- [**`np.dot(A,B)`**](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [**`np.matmul(A,B)`**](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) - Preferred
- [**`A @ B`**](https://www.python.org/dev/peps/pep-0465/) - Preferred
    
</details>

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

### 6) Cartersian coordinates to polar & spherical

#### a) Polar
[Converting between Cartesian and polar](https://en.wikipedia.org/wiki/Polar_coordinate_system#Converting_between_polar_and_Cartesian_coordinates) can be done with NumPy. 

Create a random 10x2 array with $x$ and $y$ coordinates in each column. Now convert the columns $x$, $y$ to $r$, $\phi$.

Import the following function to compare your result against:

In [ ]:
# cart2spherical takes an nx2 array as input
from lecture_functions import cart2polar

#### b) Spherical
[Converting between Cartesian and spherical](https://en.wikipedia.org/wiki/Spherical_coordinate_system#Coordinate_system_conversions) is really no different. Create a random 10x3 array with $x$, $y$, and $z$. Convert the coordinates to $r$, $\theta$, and $phi$. In this case, $\theta$ is the angle from the $z$-direction. 

Again, compare your result with the following function:

In [ ]:
# cart2spherical takes an nx3 array as input
from lecture_functions import cart2spherical

<details>
  <summary>Click here for hints</summary>
 
You might want to use the functions: [**`np.sqrt()`**](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html),
[**`np.arctan2()`**](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html),[**`np.equal()`**](https://numpy.org/doc/stable/reference/generated/numpy.equal.html)

Astropy also has the function [**`cartesian_to_spherical()`**](https://docs.astropy.org/en/stable/api/astropy.coordinates.cartesian_to_spherical.html)  
  
>*NOTE:* it gives $\theta$ measured from the $xy$-plane which can be achieved in **`np.arctan2()`** by switching the order of the arguments.
    
</details>

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

### 7) A bit of broadcasting

Run the following cell to create an array of size 4x3 and an array of size 3

In [ ]:
arr_a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
arr_b = np.array([0, 10, 100])

print(f'arr_a has shape {arr_a.shape}')
print(f'arr_b has shape {arr_b.shape}')

With these two arrays, calculate a new 4x3 array called `arr_c` where each of the rows are the rows of `arr_a` multiplied by `arr_b`. 

An illustration of the calculation you are to make:  
![](imgs/broadcasting.png)

#### Perform this calculation 
#### a) Without NumPy [broadcasting](https://numpy.org/devdocs/user/basics.broadcasting.html#basics-broadcasting)
#### b) With NumPy [broadcasting](https://numpy.org/devdocs/user/basics.broadcasting.html#basics-broadcasting)

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

## [SciPy](https://www.scipy.org)

### 1) What do I use?

SciPy contains a whole lot of different and extremely useful libraries that you will surely want to use at some point. In our line of work, SciPy quite often comes in handy. When tackling a programming problem and having to create some extensive function to perform a scientific operation or calculation, more often than not, SciPy already has that functionality.  

Below I will list a few different programming problems. Use your [Googling](www.google.com) skills to find the SciPy function which can do what is required. Once you think you have found all four, click below to see which packages I personally chose and to see how yours compare!

#### Your programming problems:
1. You have a bunch of scattered points with $(x,y)$ coordinates that you have made a 2D histogram plot of ([an example of this](https://python-graph-gallery.com/86-avoid-overlapping-in-scatterplot-with-2d-density/)). You used [**`np.histogram2d()`**](https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html) to bin the data which means your $z$-axis is the number of points in each bin.

    Now you realise that you actually want to calculate something else in the bins, perhaps the average $x$-coordinate of every point in the bin. NumPy can't do this, but a SciPy function might do..  
<br>
    <details>
      <summary>Click here for a hint</summary>

    &emsp;&emsp;Look at SciPy's statistical module [**`scipy.stats`**](https://docs.scipy.org/doc/scipy/reference/stats.html)  
    
    &emsp;&emsp; *Note:* Sometimes it's easier to find the best function by Googling!

    </details>
<br>
<br>
2. You have some data which clearly has noise. You want to fit a line through it like in the figure below. How can SciPy do this?
![](imgs/fitting.png)
<br>
    <details>
      <summary>Click here for a hint</summary>

    &emsp;&emsp;Look at SciPy's optimize module [**`scipy.optimize`**](https://docs.scipy.org/doc/scipy/reference/optimize.html)  
    
    &emsp;&emsp; *Note:* Sometimes it's easier to find the best function by Googling!

    </details>
<br>
<br>

3. You have a photo like below which unfortunately is rather pixelized. You hate pixelized images and instead want to use interpolation to get rid of the ugly bins and make it look like it does on the right. How can SciPy do this?
![](imgs/interpolate.png)
<br>
    <details>
      <summary>Click here for a hint</summary>

    &emsp;&emsp;Look at SciPy's interpolate module [**`scipy.interpolate`**](https://docs.scipy.org/doc/scipy/reference/interpolate.html)  
    
    &emsp;&emsp; *Note:* Sometimes it's easier to find the best function by Googling!

    </details>
<br>
<br>

#### The functions Daniel would choose  
<br>
<details>
  <summary>Click here to reveal!</summary>
    
You may have chosen other functions which is fine as long as they can do what is necessary. My personal picks are:
    
1. [**`scipy.stats.binned_statistic_2d()`**](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binned_statistic_2d.html#scipy.stats.binned_statistic_2d)
2. [**`scipy.optimize.curve_fit()`**](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html)
3. [**`scipy.interpolate.interp2d()`**](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html)
    
Try to understand what they can do, but don't spend too long on it.
</details>

<hr style="border:1.5px solid gray"></hr>

### 2) Least Squares with SciPy

Now you will try to use SciPy for yourself.  

Generate some noisy polynomial $x$ and $y$ data with the following function. About 100 points will suffice.

In [ ]:
from lecture_functions import polynomial_xy, plot_polynomial

x, y = polynomial_xy(100)

Visualise the data with the following function

In [ ]:
plot_polynomial(x, y)

This is clearly a 2nd order polynomial which we remember has the general equation  

$$y(x) = ax^2 + bx + c$$  

Now use the [Least squares](https://en.wikipedia.org/wiki/Least_squares) method from SciPy to fit a 2nd order polynomial and find the parameters $a$, $b$, and $c$.  

Once you are done, visualise your fit by passing the parameters to `plot_polynomial()` like:

```python
plot_polynomial(x, y, a, b, c)
```
<br>
<details>
  <summary>Click for a hint on how to set up the problem</summary>

What Least squares does is find the value of your parameters ($a$, $b$, $c$) which minimizes the residuals $r = y - y'$ where $y$ is your data and $y'$ is your fit using the parameters.  

Once you have found SciPy's least squares you will need
   1. A function to calculate the residuals
   2. An initial guess of what $a$, $b$, and $c$ are.
   2. Pass your function, the parameters, and the $(x,y)$ data to the least squares function
   3. Extract the estimated $a$, $b$, and $c$ 

</details>
<br>
<details>
  <summary>Click here for hints on the least squares function</summary>

SciPy's optimize module has [**`scipy.optimize.least_squares()`**](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html) and [**`scipy.optimize.leastsq()`**](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html). Both of these functions will work fine and can be used almost identically.  
    
Call these functions as
```python
a, b, c = least_squares(residual_function, guess_parameters, args=fixed_parameters).x # Optimal parameters are x key 
a, b, c = leastsq(residual_function, guess_parameters, args=fixed_parameters)[0] # Optimal parameters are first row
```

</details>
<br>
<details>
  <summary>Click here if you need more help</summary>

First, look at the plot and try to guess what $a$, $b$, and $c$ are and store your guesses. Ex. `guess = [a, b, c]`
  
Set up a function to calculate your residuals using your `guesss` and your data in `x` and `y`. 
```python
# guess parameters go before x, y
def residual_function(guess, x, y):
    residuals = guess[0]*x**2 + guess[1]*x + guess[2]
    return residuals
```
Now you call your least squares function from the previous hint like:
```python
least_squares(residual_function, guess, args=(x,y))    
```
    
Save the optimized parameters and check the result with `plot_polynomial()`
</details>

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>

## [AstroPy](https://www.astropy.org)


### Working with a QTable with units

In the same directory as the notebooks is a VOTable, which is a format for tabular data and very common in astronomy. 

The VOTable contains 100 stars from a simulated galaxy with position ($x$, $y$, $z$), radius ($r$) and velocities ($vx$, $vy$, $vz$) as columns

Now using AstroPy,

- [Read](https://docs.astropy.org/en/stable/io/unified.html) the VOTable into a QTable.  
<br>
- [View the table](https://docs.astropy.org/en/stable/table/#getting-started)  
<br>
- You can calculate the specific angular momentum $L_z$ for the stars with    

  $$L_z = v_y \cdot x - v_x \cdot y$$
  <br>
  Use the existing columns to add a new column containing $L_z$. What is the units of $L_z$? Does it make sense?  
<br>
<br>
- Filter the data and print only stars with radius $r < 2$ kpc.  
<br>
- Convert the $r$ column from kpc to pc.  

<br>

<details>
  <summary>Click here for hints</summary>
 
Check out [AstroPy docs on Tables](https://docs.astropy.org/en/stable/api/astropy.table.Table.html#astropy.table.Table) for a lot of useful functions such as:
[**`Table.add_column`**](https://docs.astropy.org/en/stable/api/astropy.table.Table.html#astropy.table.Table.add_column) and [**`Table.read`**](https://docs.astropy.org/en/stable/api/astropy.table.Table.html#astropy.table.Table.read)
    
You can also consult the manual for a lot of help on this exercise.
    
</details>

In [ ]:
# Your solution


<hr style="border:1.5px solid gray"></hr>
<hr style="border:1.5px solid gray"></hr>
<hr style="border:1.5px solid gray"></hr>

#### Solve SciPy 2

In [ ]:
from scipy.optimize import leastsq, curve_fit

x, y = polynomial_xy(100)
plot_polynomial(x,y)

def residuals(p, x, y):
    poly = p[0]*x**2 + p[1]*x + p[2]
    residuals = poly - y
    return residuals

g_a, g_b, g_c = 4, 2, 13
est_a, est_b, est_c = leastsq(residuals, [g_a, g_b, g_c], args=(x,y))[0]

plot_polynomial(x,y,est_a,est_b,est_c)

#### Solve AstroPy

In [ ]:
import astropy.units as u
from astropy.table import Table, QTable

In [ ]:
gt = QTable.read('galaxy.vot')

In [ ]:
gt.show_in_notebook(display_length=10)

In [ ]:
gt.add_column((gt['vy'] * gt['x'] - gt['vx'] * gt['y']), name='Lz')

In [ ]:
gt[gt['r'] < 2*u.kpc].show_in_notebook(display_length=10)

In [ ]:
gt['r'] = gt['r'].to(u.pc)
gt.show_in_notebook(display_length=10)