<img src="imgs/front.jpeg" width="1400">

<h1><center> Where to get the lecture notes </center></h1>

You can get copies of all the lecture files at my personal website. Go to:

http://www.astro.lu.se/~mikkola/

and click on **Teaching**


Each lecture contains (as notebooks)
- Manual 
- Exercises
- Presentation

---

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1920px-NumPy_logo_2020.svg.png" width="300"/>

### What is NumPy?

From [numpy.org](https://numpy.org/devdocs/user/whatisnumpy.html)

> NumPy is the fundamental package for scientific computing in Python. 


NumPy is all about the *ndarray* object which is an *n*-dimensional array of homogenous data type. I.e. one single data type. Some differences between the NumPy array and Python sequences:

- NumPy arrays have fixed size at creation
- Allows advanced mathematical operations on large data

### *ndarray* example

Let's say we have two Python lists `a` and `b`. To multiply all the elements of the first array with the corresponding elements of the second we would do perhaps:


In [1]:
a = [1, 2, 3]
b = [1, 10, 100]
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
    
print(c)

[1, 20, 300]


We can do the same thing a lot quicker in NumPy

In [2]:
import numpy as np
a = np.array(a)
b = np.array(b)
c = a * b
print(c)

[  1  20 300]


### The *ndarray*

Let's understand a few things about the ndarray. As specified, it can be $n$-dimensional

In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

Check the array shape

In [4]:
arr.shape

(2, 3)

Get the number of dimensions

In [5]:
arr.ndim

2

Total number of elements

In [6]:
arr.size

6

### Creating arrays

We can create arrays from lists and tuples, mixes of lists/tuples, or from numpy itself.

In [7]:
arr1 = np.array( [ [1, 2, 3], [4, 5, 6] ] )
arr2 = np.array( ( (1, 2, 3), (4, 5, 6) ) )
arr3 = np.array( [ (1, 2, 3), (4, 5, 6) ] )
arr4 = np.array( ( [1, 2, 3], [4, 5, 6] ) )
print(arr1, '\n')
print(arr2, '\n')
print(arr3, '\n')
print(arr4, '\n')

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]] 



In [8]:
arr1 = np.ones(3)
arr2 = np.zeros(3)
print(arr1, '\n')
print(arr2, '\n')

[1. 1. 1.] 

[0. 0. 0.] 



We can also specify the data type at creation

In [9]:
arr1 = np.array([1, 2, 3], dtype=int)
arr2 = np.array([1, 2, 3], dtype=float)
arr3 = np.array([1, 2, 3], dtype=str)
arr4 = np.array([1, 2, 3], dtype=complex)
print(arr1, '\n')
print(arr2, '\n')
print(arr3, '\n')
print(arr4, '\n')

[1 2 3] 

[1. 2. 3.] 

['1' '2' '3'] 

[1.+0.j 2.+0.j 3.+0.j] 



### Other things NumPy:
Let's quickly run through some NumPy basics

In [10]:
# Sequences
print(np.arange(0, 100, 20))
print(np.linspace(0,100,5))
print(np.logspace(0,2,5))

[ 0 20 40 60 80]
[  0.  25.  50.  75. 100.]
[  1.           3.16227766  10.          31.6227766  100.        ]


In [11]:
# Elementwise operations
A = np.array([[1, 1],[1, 1]])
B = np.array([[2, 2],[2, 2]])
print(A * B) # Elementwise
print(A @ B) # Matrix operation
print(A.dot(B)) # same matrix operation

[[2 2]
 [2 2]]
[[4 4]
 [4 4]]
[[4 4]
 [4 4]]


In [12]:
# ndarray methods
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr.sum())
print(arr.min())
print(arr.max())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
0
8


In [13]:
# Along axis
print(arr.sum(axis=0))
print(arr.min(axis=1))
print(arr.max(axis=0))

[ 9 12 15]
[0 3 6]
[6 7 8]


In [14]:
# maths
print(np.exp(2))
print(np.sqrt(9))
print(np.log(100))
print(np.log10(100))
print(np.add(2, 2))

7.38905609893065
3.0
4.605170185988092
2.0
4


### Indexing, slicing, and iterating
1-D arrays are indexed exactly like Python lists  

Multidimensional arrays have one index per axis and are accessed via tuple

In [15]:
arr = np.arange(9).reshape(3,3) 
print(arr, '\n')  

print(arr[2,2]) 
print(arr[2,:])
print(arr[2])
print(arr[:,2])
print(arr[...,2]) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

8
[6 7 8]
[6 7 8]
[2 5 8]
[2 5 8]


<img src="https://numpy.org/devdocs/_images/np_matrix_indexing.png" width="1600" style="margin: -100px 0px 0px 100px;"/>

### Shape manipulation
Change shape

In [16]:
arr = np.ones((2,6))
print(arr, '\n')

# ravel
print(arr.ravel(), '\n')

# reshape
print(arr.reshape(3,4), '\n')

# Transpose
print(arr.T, '\n')

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



Adding dimensions

In [17]:
arr = np.ones(6)
print(arr.shape, '\n')

print(arr[:,np.newaxis].shape)
print(arr[np.newaxis,:].shape, '\n')

print(np.expand_dims(arr, axis=1).shape)
print(np.expand_dims(arr, axis=0).shape)

(6,) 

(6, 1)
(1, 6) 

(6, 1)
(1, 6)


Stacking

In [22]:
# 1D arrays
arr1 = np.ones(2)
arr2 = np.zeros(2)

print(np.row_stack((arr1, arr2)), '\n')
print(np.column_stack((arr1, arr2)))

[[1. 1.]
 [0. 0.]] 

[[1. 0.]
 [1. 0.]]


In [23]:
# 2D arrays
arr1 = np.ones((2,2))
arr2 = np.zeros((2,2))

print(np.vstack((arr1, arr2)), '\n')
print(np.hstack((arr1, arr2)), '\n')

print(np.concatenate((arr1,arr2),axis=0), '\n')
print(np.concatenate((arr1,arr2),axis=1))

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]] 

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]] 

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]] 

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


### Broadcasting
Broadcasting is how NumPy treats arrays with different shapes when performing arithmetic operations. Typically it means that the smaller of the arrays is "stretched" out to match the larger's shape. For example:

<img src="https://numpy.org/devdocs/_images/np_multiply_broadcasting.png" width="1600" style="margin: -38px 0px 0px 100px;"/>

This can be rather useful for certain operations. For example consider the illustration below where we are simply doing the operation `arr_c = arr_a * arr_b`  
<br>
![](imgs/broadcasting.png)

The dimensions of two arrays are compatible with broadcasting when:
<br>
- They are equal
- One of them is 1

So let's see what works

```python
A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5
```

```python
A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5
```

```python
A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
    
```

```python
A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

### Random numbers
Using the [`numpy.random`](https://numpy.org/devdocs/reference/random/index.html#numpyrandom) module it is possible to generate random numbers from a large number of different distributions.

In [24]:
import numpy.random as random

# Random numbers between 0 and 1
print(random.rand(3), '\n')

# Random integers
print(random.randint(low=0, high=10, size=3), '\n')

# Random numbers sampled from uniform distribution
print(random.uniform(low=0, high=10, size=3), '\n')

# Random numbers sampled from Gaussian/Normal distribution
print(random.normal(size=3), '\n')

[0.2222609  0.03744311 0.03202532] 

[3 5 3] 

[2.43233931 1.11953322 1.46813883] 

[-1.87523313  0.5948798   0.25699788] 



### [SciPy](https://www.scipy.org)

A collection of mathematocal algorithms and convenience functions built on NumPy.  

![](imgs/scipy_subpackages.png)

### [Astropy](https://www.astropy.org)

Python packages developed for astronomers.  

![](imgs/astropy.png)

# Now it's time to use the manual to solve the exercises. Good luck!